### ISSUE TITLE
Can't go back to frontpage on Covfefe-logo click

### ISSUE THREAD

**Issue by pelsekongen** [Mountenberg/Covfefetime#1]
It should be possible to go back to the frontpage when I click the logo in upper left corner.

**Comment by pelsekongen** [comment]
When will this be fixed?

**Comment by pelsekongen** [comment]
I have waited a long time now

**Comment by Mountenberg** [comment]
I'm sorry omg. Try the icon now, might need to f5 page

**Comment by pelsekongen** [comment]
gg ez. thanks!
